---
title: 'Beans 2 Brew'
author: "Jyoti Yadav"
date: "11/25/2022"
chocolate crossant, spinach something, rosemary bagel
---

```{r, warning = FALSE, message = FALSE}
# Note: It is important that your answers are backed by evidence and statistical reasoning, i.e., why your answer is justified in this case. You will not get credit for merely presenting the results.

library(fpp2) # You will always load this package before analyzing any time series data.
library(tidyverse)
library(ggplot2)
library(urca)
library(seasonal)
```

```{r}
# dataset <- read_csv("./Spinach_dataset.csv",show_col_types = FALSE)
dataset <- read_csv("./Book4.csv",show_col_types = FALSE)

dataset
head(dataset)
tail(dataset)
```

```{r}
f_ts<-ts(dataset[,2], start = c(2017,3), frequency = 52)
autoplot(f_ts)
ggAcf(f_ts)
```

```{r}

# Check if time series is a white noise
Box.test(f_ts, type = "Lj",lag=10)
```

```{r}
h<-76
x_label<-"Year"
y_label<-"Qty"
plot_title<-"B2B forecast"

f_train <- window(f_ts, start=c(2017,14),end = c(2021,19))
f_test <- window(f_ts,start = c(2021,20))

fc_average <- meanf(f_train, h = h)
fc_naive <- naive(f_train, h = h)
fc_snaive <- snaive(f_train, h = h)


```

```{r}
autoplot(f_train) +
  autolayer(fc_average, series = "Mean", PI = FALSE) +
  autolayer(fc_naive, series = "Naïve", PI = FALSE) +
  autolayer(fc_snaive, series = "Seasonal naïve", PI = FALSE) +
  xlab(x_label) + ylab(y_label) +
  ggtitle(paste(plot_title, " (Benchmark methods)")) +
  guides(colour = guide_legend(title = "Forecast"))
```

```{r}
accuracy(fc_average, f_test)
accuracy(fc_naive, f_test)
accuracy(fc_snaive, f_test)
```

```{r}
theta_test <- thetaf(f_train)
theta_forecast <- forecast(theta_test)
autoplot(theta_forecast)
accuracy(theta_forecast,f_test)
```

```{r}
fit_auto<-auto.arima(f_train)
fit_auto
checkresiduals(fit_auto)
fit_auto %>% forecast(h=30) %>% autoplot(title="Auto ARIMA model")
Arima(f_test,model = fit_auto) %>% accuracy()
```

```{r}
f_arima_3 <- Arima(f_ts, order=c(0,0,0), seasonal=c(1,1,0),include.drift = TRUE)
# checkresiduals(f_arima_3)
print(" ")
Arima(f_test,model = f_arima_3) %>% accuracy()

f_arima_3
# fit_arima_3 %>% forecast(h=12) %>% autoplot()
```

```{r}
forecast<-f_arima_3 %>% forecast(h=30) 
forecast
autoplot(forecast)
```